ipmi: network: fix test failure
1. Verify IPMI Inband Network Configuration
Symptom:  fail to set LAN IP Address to 10.10.10.10
Error: LAN Parameter Data does not match! Write may have failed.
Root cause:
The command "ipmitool -C 3 -p 623 lan set 1 ipsrc static" will take some
times to remove the xyz.openbmc_project.Network.IP interface.
Fix:
Add delay after this command.

2. Get IP Address Source And Verify Using Redfish
Symptom: Fail to get attribute of /redfish/v1/Managers/bmc/EthernetInterfaces/eth1
Error: The HTTP status code was not valid
Root cause:
The Get request is unauthroized (http response code 401)
Fix:
Do Redifish.log before the Get request.

Signed-off-by: Stanley Chu <yschu@nuvoton.com>